language: php

php:
  - 7.2

install:
  - composer clear-cache
  - composer self-update
  - composer install

before_script:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin"
  - travis_retry composer install --no-interaction

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
