language: php

php:
  - 7.2

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --dev --prefer-dist --no-interaction

script:
  - /vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
